# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 547285cd4354d41eab6ff0fbd29e731d36db223a943009f447d407f907d05dc3667012a3002f1717f93c3b82751aeef7c7a93e45cdd99e1e13b67b5318916536

test:
  secret_key_base: e87ea128de4abea07ee090d938417b697e6c15bcbfdf07c1fe374b3059dce964176e55d61217e779540b195aa34bcde372c213bbf4adadd3d28f8274cd855ce8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
